---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-web-secret
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.application.auth.username | quote }}
  password: {{ .Values.application.auth.password | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-template-map
data:
  info.html.j2: |
    <!DOCTYPE html>
    <html>
    <head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.1/css/bulma.min.css" />
    </head>
    <body>
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Element</th>
        </tr>
      </thead>
      <tbody>
    {{`{% for name, element in benders.items() %}
        <tr>
          <td>{{ name }}</td>
          <td>{{ element }}</td>
        </tr>
    {% endfor %}`}}
      </tbody>
    </table>
    </body>
    </html>
