apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-aggregator
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: worker
              image: "{{ .Values.cronjob.image }}:{{ .Values.cronjob.tag }}"
              env:
                - name: REDIS_URL
                  value: "redis://{{ .Release.Name }}-redis:{{ .Values.redis.port }}/0"
          imagePullSecrets:
            - name: docker-registry-registrycreds
          restartPolicy: Never
