apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-api-ingress
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt-prod
spec:
  rules:
    - host: {{ .Values.application.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.application.ingress.path | quote }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-web
                port:
                  number: {{ .Values.web.port }}
  tls:
    - hosts:
        - {{ .Values.application.ingress.host }}
      secretName: {{ .Values.application.ingress.secretName }}
