---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-web
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-web
    spec:
      containers:
        - name: web
          image: "{{ .Values.web.image }}:{{ .Values.web.tag }}"
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: template-map
              mountPath: /templates
          env:
            - name: REDIS_URL
              value: "redis://{{ .Release.Name }}-redis:{{ .Values.redis.port }}/0"
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-web-secret
                  key: username
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-web-secret
                  key: password
      imagePullSecrets:
        - name: docker-pull-secret
      volumes:
        - name: template-map
          configMap:
            name: {{ .Release.Name }}-template-map
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
spec:
  selector:
    app: {{ .Release.Name }}-web
  ports:
    - port: {{ .Values.web.port }}
      targetPort: 8000
